version: '3.8'

services:
  web:
    build: .
    container_name: djangogoat-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: djangogoat-db
    restart: always
    environment:
      POSTGRES_DB: djangogoat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
